apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: python-dynam-lab-secret
  namespace: python-dynamo-lab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretmanager
    kind: SecretStore
  target:
    name: python-dynamo-lab-app-secret   # Kubernetes Secret ESO will create
    creationPolicy: Owner                # ESO owns this secret, deletes it if ExternalSecret deleted
  data:
  - secretKey: API_KEY
    remoteRef:
      key: python-dynamo-lab/api-key     # path in AWS Secrets Manager
      property: API_KEY                  # field inside the secret JSON
