# yaml-language-server: $schema=kubernetes
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: python-dynamo-lab
spec:
  provider:
    aws:
      service: SecretManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: python-dynamo-lab-sa
