apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://host.docker.internal:8200"
      path: "kv/org"
      version:
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "python-dynamo-lab"
          key: "token"



## encrypted K8s Secret, not just Base64 encoded.

# Create a Kubernetes secret with the Vault token
# kubectl create secret generic vault-token \
#   --namespace python-dynamo-lab" \
#   --from-literal=token=root
