# yaml-language-server: $schema=kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-dynamo-lab-sa
  namespace: python-dynamo-lab
  annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
