# yaml-language-server: $schema=kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-dynamo-sa
  namespace: python-dynamo-lab
  annotations:
    "eks.amazonaws.com/role-arn: IRSA role

  labels:
    app: app-name
automountServiceAccountToken: false
imagePullSecrets:
  - name: regcred
