name: Scan CI on pull request
on: pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip isntall --upgrade pip
          pip install -r app/requirements.txt

      - name: run tests
        run: pytest app/tests/test-api.py --cov=app --cov-fail-under=80 --cov-report=xml:app/coverage.xml

      - name: upload coverage
        uses: action/upload-artifact@v7
        with:
          name: coverage-xml
          path: app/coverage.xml

  code-quality:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: download coverage report
        with:
          name: coverage-xml
          path: app
      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          projectBaseDir: app
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=tests/
            -Dsonar.test.exclusions=tests/**
            -Dsonar.verbose=true
          env:
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
            SONAR_HOST_URL: ${{vars.SONAR_HOST_URL}}

  security-scan:
    runs-on: ubuntu-server
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: app/
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,critical'

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'


  # security-scan:
  #   runs-on: ubuntu-server
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Snyk CLI
  #       uses: npm isntall -g snyk

  #     - name: Authenticate Snyk
  #       run: snyk auth ${{ secrets.SNYK_TOKEN }}

  #     - name: Run Snyk Test (Local Dependency Scan)
  #       run: |
  #         cd app
  #         # Scan dependencies for vulnerabilities
  #         snyk test --file=requirements.txt --severity-threshold=high

  #     - name: Run Snyk Monitor (Optional: Updates Snyk Dashboard)
  #       run: |
  #         cd app
  #         snyk monitor --file=requirements.txt
  #       if: github.ref == 'refs/heads/main'
